version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
     - "15672:15672"
     - "5672:5672"
     - "4369:4369"
  redis:
    image: redis
    ports:
     - "6379:6379"
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
