version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-tox-

      - run:
          name: install dependencies
          command: |
            sudo pip install tox

      - run:
          name: run tests
          command: |
            tox

      # Save tox and venv cache
      - save_cache:
          paths:
            - ./.tox
          key: v1-tox

      - run:
          name: submit coverage
          command: pipenv run coveralls

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  distribute:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-venv-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install -d
      - run:
          name: generate packages
          command: |
            pipenv run python setup.py sdist bdist_wheel
      - run:
          name: upload packages to Pypi
          command: |
            pipenv run twine upload dist/*
workflows:
  version: 2
  build-distribute:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/ # This is needed so that tags are also built when pushed
      - distribute:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
